import json
import re

# Load data
with open('data/syllabus.json', 'r', encoding='utf-8') as f:
    syllabus = json.load(f)

# Extract IDs and View names from LEARNING_OBJECTIVES
with open('data/learningObjectives.ts', 'r', encoding='utf-8') as f:
    ts_content = f.read()

covered_map = {}
matches = re.finditer(r"id:\s*'([\d\.]+)',.*?coveredBy:\s*View\.([A-Z_0-9]+)", ts_content, re.DOTALL)
for m in matches:
    covered_map[m.group(1)] = m.group(2)

# Helper to normalize code: "062 01 01 00" -> "062.01.01"
def code_to_id(code):
    if not code: return ""
    parts = code.split()
    while parts and parts[-1] == '00':
        parts.pop()
    return ".".join(parts)

def check_node(node, path="", inherited_coverage=None):
    node_id = code_to_id(node.get('code', ''))
    title = node.get('title', 'Unknown')
    
    # Check if THIS node is explicitly covered
    direct_coverage = covered_map.get(node_id)
    if not direct_coverage and node.get('id') and node.get('id') in covered_map:
        direct_coverage = covered_map[node.get('id')]

    # Resolve effective coverage
    effective_coverage = direct_coverage or inherited_coverage
    
    result = []
    
    # If I am not covered, I am missing.
    if not effective_coverage:
        # We only care about level 2+ (Topics) to avoid clutter, unless it's a high level subject that is completely missing
        depth = len(node_id.split('.'))
        
        if depth >= 2:
             return [f"[{node_id}] {title}"]
    
    if effective_coverage and not inherited_coverage:
        # I am the start of a covered branch.
        return []

    # Recurse
    child_results = []
    if 'children' in node:
        for child in node['children']:
            child_results.extend(check_node(child, path + " > " + title, effective_coverage))
            
    if 'los' in node: 
        for lo in node['los']:
             child_results.extend(check_node(lo, path + " > " + title, effective_coverage))
             
    return child_results

todo_list = []
for subject in syllabus:
    items = check_node(subject)
    if items:
        # Only add header if there are items
        header = f"\n--- Subject {subject['code']} {subject['title']} ---"
        todo_list.append(header)
        todo_list.extend(items)

with open('syllabus_todo_list_v2.txt', 'w', encoding='utf-8') as f:
    f.write("Syllabus Gaps To-Do List (High Level)\n")
    f.write("Generated by analyzing syllabus.json vs learningObjectives.ts with Inheritance\n")
    f.write("==============================================================================\n")
    if not todo_list:
        f.write("No major gaps found! Everything seems covered by high-level modules.\n")
    else:
        for line in todo_list:
            f.write(line + "\n")

print("To-Do list generated: syllabus_todo_list_v2.txt")
