import React from 'react';
import { View } from '../types';

// Lazy Load Components
export const routes: Record<string, React.LazyExoticComponent<any>> = {
    // Platform Level
    [View.PLATFORM_DASHBOARD]: React.lazy(() => import('../components/PlatformDashboard')),
    [View.PROFILE]: React.lazy(() => import('../components/UserProfile')),
    [View.ACCOUNT_SETTINGS]: React.lazy(() => import('../components/AccountSettings')),
    [View.FLASHCARDS]: React.lazy(() => import('../components/FlashcardSystem')),
    [View.SUBSCRIPTION_MANAGEMENT]: React.lazy(() => import('../components/SubscriptionManagement')),
    [View.ADMIN_DASHBOARD]: React.lazy(() => import('../components/AdminDashboard')),
    [View.STUDY_GUIDE]: React.lazy(() => import('../components/StudyGuide')),
    [View.QUESTION_BANK]: React.lazy(() => import('../components/QuestionBank')),
    [View.EXAM_PLANNER]: React.lazy(() => import('../components/ExamPlanner').then(module => ({ default: module.ExamPlanner }))),
    [View.SYLLABUS_VIEWER]: React.lazy(() => import('../components/SyllabusViewer')),
    [View.PROGRESS_DASHBOARD]: React.lazy(() => import('../components/ProgressDashboard')),
    [View.PLATFORM_PROGRESS]: React.lazy(() => import('../components/PlatformProgress')),
    // [View.SAFE_FLIGHTS]: React.lazy(() => import('../components/SafeFlights/SafeFlightsApp')), // TODO: Port SafeFlights from separate project

    // Concepts
    [View.CONCEPT_FORCES_OF_FLIGHT]: React.lazy(() => import('../components/concepts/ForcesOfFlight')),
    [View.CONCEPT_HOLD_ENTRY]: React.lazy(() => import('../components/concepts/HoldEntryVisualizer')),
    [View.CONCEPT_GREAT_CIRCLE]: React.lazy(() => import('../components/concepts/GreatCircleExplorer')),
    [View.CONCEPT_TURN_PERF]: React.lazy(() => import('../components/concepts/TurnPerformance')),

    // Air Law (010)
    [View.AIR_LAW_HOME]: React.lazy(() => import('../components/AirLawDashboard')),
    [View.AIR_LAW_ORG]: React.lazy(() => import('../components/AviationOrganisations')),
    [View.AIR_LAW_INT_LAW]: React.lazy(() => import('../components/InternationalLaw')),
    [View.AIR_LAW_LIABILITY]: React.lazy(() => import('../components/LiabilityAndRights')),
    [View.AIR_LAW_ANNEXES]: React.lazy(() => import('../components/AnnexList')),
    [View.AIR_LAW_PERSONNEL]: React.lazy(() => import('../components/PersonnelLicensing')),
    [View.AIR_LAW_AIRWORTHINESS]: React.lazy(() => import('../components/AirworthinessAndOps')),
    [View.AIR_LAW_REGISTRATION]: React.lazy(() => import('../components/AircraftRegistration')),
    [View.AIR_LAW_DOCS]: React.lazy(() => import('../components/DocumentsOnboard')),
    [View.AIR_LAW_RULES_DETAILS]: React.lazy(() => import('../components/RulesOfTheAirDetails')),
    [View.AIR_LAW_RULES_OF_AIR]: React.lazy(() => import('../components/AirLawRightOfWay')),
    [View.AIR_LAW_CRUISING]: React.lazy(() => import('../components/CruisingLevelTool')),
    [View.AIR_LAW_INTERCEPT]: React.lazy(() => import('../components/InterceptionProcedures')),
    [View.AIR_LAW_LIGHTGUN]: React.lazy(() => import('../components/LightGunSignals')),
    [View.AIR_LAW_LAYERS]: React.lazy(() => import('../components/AirspaceLayers')),
    [View.AIR_LAW_IFR_VFR]: React.lazy(() => import('../components/IFRVFRExplorer')),
    [View.AIR_LAW_INSTRUMENT]: React.lazy(() => import('../components/InstrumentApproach')),
    [View.AIR_LAW_PANS_OPS]: React.lazy(() => import('../components/PansOpsProcedures')),
    [View.AIR_LAW_HOLDING]: React.lazy(() => import('../components/HoldingPatternEntry')),
    [View.AIR_LAW_ALTIMETER]: React.lazy(() => import('../components/AltimeterVisualizer')),
    [View.AIR_LAW_REF_CODE]: React.lazy(() => import('../components/AerodromeReferenceCode')),
    [View.AIR_LAW_SURFACE_CON]: React.lazy(() => import('../components/SurfaceContamination')),
    [View.AIR_LAW_LIGHTING]: React.lazy(() => import('../components/AerodromeLightingSummary')),
    [View.AIR_LAW_AERODROME_VIS]: React.lazy(() => import('../components/AerodromeVisualizer')),
    [View.AIR_LAW_SIGNS]: React.lazy(() => import('../components/SignsAndSignals')),
    [View.AIR_LAW_GROUND_OPS]: React.lazy(() => import('../components/GroundOperations')),
    [View.AIR_LAW_RWSL]: React.lazy(() => import('../components/RWSL')),
    [View.AIR_LAW_TVASIS]: React.lazy(() => import('../components/TVasisVisualizer')),
    [View.AIR_LAW_DECLARED_DIST]: React.lazy(() => import('../components/DeclaredDistances')),
    [View.AIR_LAW_OPS_INFO]: React.lazy(() => import('../components/OperationalInfo')),
    [View.AIR_LAW_SECURITY]: React.lazy(() => import('../components/SecuritySection')),
    [View.AIR_LAW_ACCIDENT]: React.lazy(() => import('../components/AccidentInvestigation')),
    [View.AIR_LAW_SAR]: React.lazy(() => import('../components/SearchAndRescue')),
    [View.AIR_LAW_EMERGENCY]: React.lazy(() => import('../components/EmergencyProcedures')),
    [View.AIR_LAW_FACILITATION]: React.lazy(() => import('../components/AirLawFacilitation')),
    [View.AIR_LAW_PARALLEL_RWY]: React.lazy(() => import('../components/AirLawParallelRunway')),
    [View.AIR_LAW_AIS_DEEP_DIVE]: React.lazy(() => import('../components/AirLawAISDeepDive')),
    [View.AIR_LAW_CONVENTIONS]: React.lazy(() => import('../components/AirLawConventions')),

    // AGK (021/022)
    [View.AGK_SYSTEMS_HOME]: React.lazy(() => import('../components/GenericSubjectDashboard')),
    [View.AGK_HYDRAULICS]: React.lazy(() => import('../components/AGK/HydraulicSystemAnim')),
    [View.AGK_JET_ENGINE]: React.lazy(() => import('../components/AGK/JetEnginePrinciples')),
    [View.AGK_ELECTRICS]: React.lazy(() => import('../components/AGK/ElectricsSystem')),
    [View.AGK_PISTON_ENGINE]: React.lazy(() => import('../components/AGK/PistonEnginePrinciples')),
    [View.AGK_LANDING_GEAR]: React.lazy(() => import('../components/AGK/LandingGearSystem')),
    [View.AGK_FLIGHT_CONTROLS]: React.lazy(() => import('../components/AGK/FlightControlsSystem')),
    [View.AGK_SYSTEMS_OXYGEN]: React.lazy(() => import('../components/021-agk-systems/OxygenSystems')),

    // Instrumentation (022)
    [View.INST_HOME]: React.lazy(() => import('../components/GenericSubjectDashboard')),
    [View.INST_PITOT_STATIC]: React.lazy(() => import('../components/Instrumentation/PitotStaticSystem')),
    [View.INST_ALTIMETER]: React.lazy(() => import('../components/Instrumentation/AltimeterLab')),
    [View.INST_ASI]: React.lazy(() => import('../components/Instrumentation/AirspeedIndicator')),
    [View.INST_VSI]: React.lazy(() => import('../components/Instrumentation/VSILab')),
    [View.INST_MACHMETER]: React.lazy(() => import('../components/Instrumentation/Machmeter')),
    [View.INST_GYROS]: React.lazy(() => import('../components/Instrumentation/GyroPrinciples')),
    [View.INST_TURN_INDICATOR]: React.lazy(() => import('../components/Instrumentation/TurnIndicator')),
    [View.INST_DG]: React.lazy(() => import('../components/Instrumentation/DirectionalGyro')),
    [View.INST_ATTITUDE]: React.lazy(() => import('../components/Instrumentation/AttitudeIndicator')),
    [View.INST_COMPASS]: React.lazy(() => import('../components/Instrumentation/MagneticCompass')),
    [View.INST_RADIO_ALT]: React.lazy(() => import('../components/Instrumentation/RadioAltimeter')),
    [View.INST_NAV_SYSTEMS]: React.lazy(() => import('../components/Instrumentation/NavigationSystems')),
    [View.INST_FMS_EFIS]: React.lazy(() => import('../components/Instrumentation/FMSEFIS')),
    [View.INST_GPWS]: React.lazy(() => import('../components/Instrumentation/GPWSSystem')),
    [View.INST_AUTOPILOT]: React.lazy(() => import('../components/Instrumentation/AutopilotSystem')),
    [View.INST_AUTOLAND]: React.lazy(() => import('../components/Instrumentation/AutolandSystem')),

    // Mass & Balance (031)
    [View.MASS_BAL_HOME]: React.lazy(() => import('../components/GenericSubjectDashboard')),
    [View.MASS_BAL_DEFINITIONS]: React.lazy(() => import('../components/MassBal/MassDefinitions')),
    [View.MASS_BAL_CG_CALC]: React.lazy(() => import('../components/MassBal/WeighingProcedure')),
    [View.MASS_BAL_LIMITS]: React.lazy(() => import('../components/MassBal/LoadingLimits')),
    [View.MASS_BAL_MAC]: React.lazy(() => import('../components/MassBal/MacVisualizer')),
    [View.MASS_BAL_FUEL]: React.lazy(() => import('../components/MassBal/FuelDensityCalc')),
    [View.MASS_BAL_SHIFT]: React.lazy(() => import('../components/MassBal/CargoHandlingSim')),
    [View.MASS_BAL_LOADSHEET]: React.lazy(() => import('../components/MassBal/LoadSheetSim')),
    [View.MASS_BAL_FLOW_DIAGRAM]: React.lazy(() => import('../components/MassBal/MassBuildUpFlow')),
    [View.MASS_BAL_TRIM_SHEET]: React.lazy(() => import('../components/MassBal/TrimSheetSim')),
    [View.MASS_BAL_CG_SHIFT]: React.lazy(() => import('../components/MassBal/CGShiftVisualizer')),
    [View.MASS_BAL_CONVERTER]: React.lazy(() => import('../components/MassBal/UnitConverter')),
    [View.MASS_BAL_EFFECTS]: React.lazy(() => import('../components/MassBal/MassEffects')),
    [View.MASS_BAL_CG_EFFECTS]: React.lazy(() => import('../components/MassBal/CGEffects')),
    [View.MASS_BAL_STRUCTURAL]: React.lazy(() => import('../components/MassBal/StructuralLimits')),
    [View.MASS_BAL_STALL_SPEED]: React.lazy(() => import('../components/MassBal/StallSpeedCalc')),
    [View.MASS_BAL_FLEET]: React.lazy(() => import('../components/MassBal/FleetMasses')),
    [View.MASS_BAL_CARGO_TYPES]: React.lazy(() => import('../components/MassBal/CargoTypes')),
    [View.MASS_BAL_STD_MASSES]: React.lazy(() => import('../components/MassBal/StandardMasses')),
    [View.MASS_BAL_QUIZ]: React.lazy(() => import('../components/MassBal/MassBalanceQuizWizard')),

    // HPL (040)
    [View.HPL_HOME]: React.lazy(() => import('../components/GenericSubjectDashboard')),
    [View.HPL_PHYSIOLOGY]: React.lazy(() => import('../components/HPL/HumanPhysiology')),
    [View.HPL_BASIC_CONCEPTS]: React.lazy(() => import('../components/HPL/HumanFactorsIntro')),
    [View.HPL_SLEEP]: React.lazy(() => import('../components/HPL/SleepAndRhythms')),
    [View.HPL_INFO_PROCESSING]: React.lazy(() => import('../components/HPL/InformationProcessing')),
    [View.HPL_ERROR_DECISION]: React.lazy(() => import('../components/HPL/ErrorAndDecision')),
    [View.HPL_COCKPIT_MGMT]: React.lazy(() => import('../components/HPL/CockpitManagement')),
    [View.HPL_COMMS_STRESS]: React.lazy(() => import('../components/HPL/CommunicationAndStress')),
    [View.HPL_BEHAVIOUR]: React.lazy(() => import('../components/HPL/HumanBehaviour')),
    [View.HPL_VISION]: React.lazy(() => import('../components/HPL/HPLVision')),
    [View.HPL_HEARING]: React.lazy(() => import('../components/HPL/HPLHearing')),
    [View.HPL_HEALTH]: React.lazy(() => import('../components/HPL/HPLHealth')),
    [View.HPL_TEM]: React.lazy(() => import('../components/HPL/HPLTEM')),
    [View.HPL_SHELL]: React.lazy(() => import('../components/HPL/HPLShell')),
    [View.HPL_SAFETY]: React.lazy(() => import('../components/HPL/HPLSafetyCulture')),
    [View.HPL_ACCELERATION]: React.lazy(() => import('../components/HPL/HPLAcceleration')),
    [View.HPL_TOXIC]: React.lazy(() => import('../components/HPL/HPLToxicHazards')),
    [View.HPL_AUTOMATION]: React.lazy(() => import('../components/HPL/HPLAutomation')),
    [View.HPL_VESTIBULAR]: React.lazy(() => import('../components/HPL/HPLVestibular')),
    [View.HPL_MEMORY]: React.lazy(() => import('../components/HPL/HPLMemory')),
    [View.HPL_RESPIRATION]: React.lazy(() => import('../components/HPL/HPLRespiration')),
    [View.HPL_CIRCULATION]: React.lazy(() => import('../components/HPL/HPLCirculation')),
    [View.HPL_NERVOUS]: React.lazy(() => import('../components/HPL/HPLNervousSystem')),
    [View.HPL_METABOLISM]: React.lazy(() => import('../components/HPL/HPLMetabolism')),
    [View.HPL_ERGONOMICS]: React.lazy(() => import('../components/HPL/HPLErgonomics')),
    [View.HPL_BIASES]: React.lazy(() => import('../components/HPL/HPLBiases')),
    [View.HPL_CULTURE]: React.lazy(() => import('../components/HPL/HPLCulture')),
    [View.HPL_RADIATION]: React.lazy(() => import('../components/HPL/HPLRadiation')),
    [View.HPL_THERMAL]: React.lazy(() => import('../components/HPL/HPLThermal')),
    [View.HPL_SLEEP_DISORDERS]: React.lazy(() => import('../components/HPL/HPLSleepDisorders')),
    [View.HPL_WORKLOAD]: React.lazy(() => import('../components/HPL/HPLWorkload')),
    [View.HPL_PERSONALITY]: React.lazy(() => import('../components/HPL/HPLPersonality')),
    [View.HPL_LEARNING]: React.lazy(() => import('../components/HPL/HPLLearning')),
    [View.HPL_PERCEPTION]: React.lazy(() => import('../components/HPL/HPLPerception')),
    [View.HPL_COMMUNICATION_PROCESS]: React.lazy(() => import('../components/HPL/HPLCommunicationProcess')),
    [View.HPL_COOPERATION]: React.lazy(() => import('../components/HPL/HPLCooperation')),
    [View.HPL_COMPETENCY]: React.lazy(() => import('../components/HPL/HPLCompetency')),
    [View.HPL_MOTION_SICKNESS]: React.lazy(() => import('../components/HPL/HPLMotionSickness')),
    [View.HPL_PRESSURE]: React.lazy(() => import('../components/HPL/HPLPressure')),
    [View.HPL_ATMOSPHERE]: React.lazy(() => import('../components/HPL/HPLAtmosphere')),
    [View.HPL_HEALTH_HYGIENE]: React.lazy(() => import('../components/HPL/HPLHealthHygiene')),
    [View.HPL_INCIDENTS]: React.lazy(() => import('../components/HPL/HPLIncidents')),
    [View.HPL_INCAPACITATION]: React.lazy(() => import('../components/HPL/HPLIncapacitation')),
    [View.HPL_TROPICAL_DISEASES]: React.lazy(() => import('../components/HPL/HPLTropicalDiseases')),

    // Meteorology (050)
    [View.MET_HOME]: React.lazy(() => import('../components/Meteorology/MetDashboard')),
    [View.MET_ATMOSPHERE]: React.lazy(() => import('../components/Meteorology/AtmosphereMaster')),
    [View.MET_TEMPERATURE]: React.lazy(() => import('../components/Meteorology/MetThermodynamics')),
    [View.MET_PRESSURE]: React.lazy(() => import('../components/Meteorology/PressureSystems')),
    [View.MET_DENSITY]: React.lazy(() => import('../components/Meteorology/Density')),
    [View.MET_ALTIMETRY]: React.lazy(() => import('../components/Meteorology/Altimetry')),
    [View.MET_WIND]: React.lazy(() => import('../components/Meteorology/WindSystems')),
    [View.MET_CIRCULATION]: React.lazy(() => import('../components/Meteorology/GeneralCirculation')),
    [View.MET_HUMIDITY]: React.lazy(() => import('../components/Meteorology/HumidityLab')),
    [View.MET_PRECIPITATION]: React.lazy(() => import('../components/Meteorology/Precipitation')),
    [View.MET_FRONTS]: React.lazy(() => import('../components/Meteorology/FrontalSystems')),
    [View.MET_THUNDERSTORMS]: React.lazy(() => import('../components/Meteorology/Thunderstorms')),
    [View.MET_ICING]: React.lazy(() => import('../components/Meteorology/Icing')),
    [View.MET_VISIBILITY]: React.lazy(() => import('../components/Meteorology/VisibilityFog')),
    [View.MET_AIR_MASSES]: React.lazy(() => import('../components/Meteorology/AirMasses')),
    [View.MET_TURBULENCE]: React.lazy(() => import('../components/Meteorology/Turbulence')),
    [View.MET_JET_STREAMS]: React.lazy(() => import('../components/Meteorology/JetStreams')),
    [View.MET_CLIMATOLOGY]: React.lazy(() => import('../components/Meteorology/Climatology')),
    [View.MET_LOCAL_WINDS]: React.lazy(() => import('../components/Meteorology/LocalWinds')),
    [View.MET_DEPRESSIONS_ANTICYCLONES]: React.lazy(() => import('../components/Meteorology/DepressionsAnticyclones')),
    [View.MET_CLOUD_TYPES]: React.lazy(() => import('../components/Meteorology/CloudTypes')),
    [View.MET_METAR_TAF]: React.lazy(() => import('../components/Meteorology/MetarTafDecoder')),
    [View.MET_CHARTS]: React.lazy(() => import('../components/Meteorology/WeatherCharts')),
    [View.MET_TRS]: React.lazy(() => import('../components/Meteorology/TropicalStorms')),
    [View.MET_SPECIAL_HAZARDS]: React.lazy(() => import('../components/Meteorology/SpecialHazards')),
    [View.MET_SATELLITE]: React.lazy(() => import('../components/Meteorology/SatelliteRadar')),
    [View.MET_OPTICAL]: React.lazy(() => import('../components/Meteorology/OpticalPhenomena')),
    [View.MET_STATION_MODEL]: React.lazy(() => import('../components/Meteorology/StationModels')),

    // Gen Nav (061)
    [View.GEN_NAV_HOME]: React.lazy(() => import('../components/GenericSubjectDashboard')),
    [View.GEN_NAV_TIME]: React.lazy(() => import('../components/GenNav/SolarCalc')),
    [View.GEN_NAV_CHARTS]: React.lazy(() => import('../components/GenNav/MapProjections')),
    [View.GEN_NAV_VFR]: React.lazy(() => import('../components/GenNav/WindTriangle')),
    [View.GEN_NAV_EARTH]: React.lazy(() => import('../components/GenNav/EarthGeometry')),
    [View.GEN_NAV_BASICS]: React.lazy(() => import('../components/GenNav/EarthGeometry')),
    [View.GEN_NAV_MAPS]: React.lazy(() => import('../components/GenNav/MapProjections')),
    [View.GEN_NAV_SOLAR]: React.lazy(() => import('../components/GenNav/SolarCalc')),
    [View.NAV_60_1]: React.lazy(() => import('../components/Nav/OneInSixty')),

    // Radio Nav (062)
    [View.RAD_NAV_HOME]: React.lazy(() => import('../components/GenericSubjectDashboard')),
    [View.NAV_GNSS]: React.lazy(() => import('../components/RadioNav/GNSSTheory')),
    [View.RAD_NAV_WAVE_PROP]: React.lazy(() => import('../components/RadioNav/WavePropVisualizer')),
    [View.RAD_NAV_SPECTRUM]: React.lazy(() => import('../components/RadioNav/SpectrumExplorer')),
    [View.RAD_NAV_IONOSPHERE]: React.lazy(() => import('../components/RadioNav/IonosphereSim')),
    [View.RAD_NAV_ANTENNA]: React.lazy(() => import('../components/RadioNav/AntennaTheory')),
    [View.RAD_NAV_MODULATION]: React.lazy(() => import('../components/RadioNav/Modulation')),
    [View.RAD_NAV_VOR]: React.lazy(() => import('../components/RadioNav/VORSystem')),
    [View.RAD_NAV_ADF]: React.lazy(() => import('../components/RadioNav/NDBADFSystem')),
    [View.RAD_NAV_DME]: React.lazy(() => import('../components/RadioNav/DMESystem')),
    [View.RAD_NAV_ILS]: React.lazy(() => import('../components/RadioNav/ILSSystem')),
    [View.RAD_NAV_VDF]: React.lazy(() => import('../components/RadioNav/VDF')),
    [View.RAD_NAV_MLS]: React.lazy(() => import('../components/RadioNav/MLS')),
    [View.RAD_NAV_RADAR]: React.lazy(() => import('../components/RadioNav/RadarTheory')),
    [View.RAD_NAV_WX_RADAR]: React.lazy(() => import('../components/RadioNav/WeatherRadar')),
    [View.RAD_NAV_SSR]: React.lazy(() => import('../components/RadioNav/SSRTransponder')),
    [View.RAD_NAV_SBAS]: React.lazy(() => import('../components/RadioNav/SbasAbas')),
    [View.RAD_NAV_RNAV]: React.lazy(() => import('../components/RadioNav/RnavPbn')),
    [View.RAD_NAV_FMS]: React.lazy(() => import('../components/RadioNav/FMSTrainer')),
    [View.RAD_NAV_CLASS_1]: React.lazy(() => import('../components/RadioNav/RadioFundamentals')),

    // Principles of Flight (081)
    [View.POF_HOME]: React.lazy(() => import('../components/GenericSubjectDashboard')),
    [View.POF_ATMOSPHERE]: React.lazy(() => import('../components/PoF/AtmosphereProp')),
    [View.POF_AIRFLOW]: React.lazy(() => import('../components/PoF/AirflowBasics')),
    [View.POF_AEROFOIL]: React.lazy(() => import('../components/PoF/AerofoilGeom')),
    [View.POF_WING_GEOM]: React.lazy(() => import('../components/PoF/WingGeom')),
    [View.POF_LIFT_DRAG]: React.lazy(() => import('../components/PoF/LiftDragCoeff')),
    [View.POF_3D_AIRFLOW]: React.lazy(() => import('../components/PoF/ThreeDAirflow')),
    [View.POF_DRAG]: React.lazy(() => import('../components/PoF/TotalDrag')),
    [View.POF_GROUND_EFFECT]: React.lazy(() => import('../components/PoF/GroundEffect')),
    [View.POF_HIGH_LIFT]: React.lazy(() => import('../components/PoF/HighLiftDevices')),
    [View.POF_STALL]: React.lazy(() => import('../components/PoF/LiftDragCoeff')),
    [View.POF_HIGH_SPEED]: React.lazy(() => import('../components/PoF/PoFHighSpeed')),
    [View.POF_CONTROL]: React.lazy(() => import('../components/PoF/PoFControl')),
    [View.POF_LIMITATIONS]: React.lazy(() => import('../components/PoF/PoFLimitations')),
    [View.POF_PROPELLERS]: React.lazy(() => import('../components/PoF/PoFPropellers')),
    [View.POF_FLIGHT_MECHANICS]: React.lazy(() => import('../components/PoF/PoFFlightMechanics')),

    // Principles of Flight - Helicopters (082)
    [View.POF_HELI_HOME]: React.lazy(() => import('../components/GenericSubjectDashboard')),
    [View.POF_HELI_SUBSONIC]: React.lazy(() => import('../components/PoFHeli/SubsonicAero')),
    [View.POF_HELI_TRANSONIC]: React.lazy(() => import('../components/PoFHeli/TransonicAero')),
    [View.POF_HELI_ROTORCRAFT_TYPES]: React.lazy(() => import('../components/PoFHeli/RotorcraftTypes')),
    [View.POF_HELI_MAIN_ROTOR_AERO]: React.lazy(() => import('../components/PoFHeli/MainRotorAero')),
    [View.POF_HELI_MAIN_ROTOR_MECH]: React.lazy(() => import('../components/PoFHeli/MainRotorMech')),
    [View.POF_HELI_TAIL_ROTORS]: React.lazy(() => import('../components/PoFHeli/TailRotors')),
    [View.POF_HELI_EQUILIBRIUM]: React.lazy(() => import('../components/PoFHeli/Equilibrium')),
    [View.POF_HELI_FLIGHT_MECH]: React.lazy(() => import('../components/PoFHeli/FlightMech')),

    // Communications (090)
    [View.DASHBOARD]: React.lazy(() => import('../components/Comms/CommsDashboard')),
    [View.GENERAL_THEORY]: React.lazy(() => import('../components/GeneralTheory')),
    [View.PROPAGATION_THEORY]: React.lazy(() => import('../components/Comms/PropagationTheory')),
    [View.TECH_PHYSICS]: React.lazy(() => import('../components/TechPhysics')),
    [View.FREQ_EXPLORER]: React.lazy(() => import('../components/FrequencyExplorer')),
    [View.SUFFIX_MATCH]: React.lazy(() => import('../components/SuffixMatch')),
    [View.QCODE_CARDS]: React.lazy(() => import('../components/QCodeFlashcards')),
    [View.Q_COMPASS]: React.lazy(() => import('../components/QCodeCompass')),
    [View.WORD_MATCH]: React.lazy(() => import('../components/WordMatch')),
    [View.PHONETIC]: React.lazy(() => import('../components/PhoneticTrainer')),
    [View.ALT_SPEAK]: React.lazy(() => import('../components/AltSpeak')),
    [View.TIME_REPORT]: React.lazy(() => import('../components/TimeReport')),
    [View.READABILITY_SIM]: React.lazy(() => import('../components/Comms/ReadabilitySim')),
    [View.FLIGHT_RULES]: React.lazy(() => import('../components/FlightRules')),
    [View.PRIORITY]: React.lazy(() => import('../components/Comms/PrioritySorter')),
    [View.CALLSIGN_TRAINER]: React.lazy(() => import('../components/Comms/CallsignTrainer')),
    [View.URGENCY_TRAINER]: React.lazy(() => import('../components/Comms/UrgencyTrainer')),
    [View.LEVEL_CHANGES]: React.lazy(() => import('../components/Comms/LevelChanges')),
    [View.ABBREVIATION_GAME]: React.lazy(() => import('../components/Comms/AbbreviationGame')),
    [View.CPDLC_SIM]: React.lazy(() => import('../components/Comms/CPDLCSim')),
    [View.READBACK]: React.lazy(() => import('../components/ReadbackChallenge')),
    [View.METAR]: React.lazy(() => import('../components/MetarDecoder')),
    [View.VOLMET_SIM]: React.lazy(() => import('../components/Comms/VolmetSimulator')),
    [View.AIREP_SPEC]: React.lazy(() => import('../components/AirepSpec')),
    [View.RADIO_NAV_DATA]: React.lazy(() => import('../components/NavDataLink')),
    [View.TIME_ZONER]: React.lazy(() => import('../components/TimeZoner')),
    [View.EMERGENCY]: React.lazy(() => import('../components/EmergencyBuilder')),
    [View.EMERGENCY_OPS]: React.lazy(() => import('../components/EmergencyOps')),
    [View.COMM_FAIL]: React.lazy(() => import('../components/CommFailure')),
    [View.BLIND_TX]: React.lazy(() => import('../components/BlindTrans')),
    [View.TRANSPONDER]: React.lazy(() => import('../components/TransponderDojo')),
    [View.VFR_COMMS_SIM]: React.lazy(() => import('../components/Comms/VfrFlightSim')),
    [View.PHRASEOLOGY_EXPLORER]: React.lazy(() => import('../components/PhraseologyExplorer')),
    [View.POS_REPORT]: React.lazy(() => import('../components/PositionReport')),
    [View.TRAFFIC_CLOCK]: React.lazy(() => import('../components/TrafficClock')),
    [View.AI_ROLEPLAY]: React.lazy(() => import('../components/ScenarioRoleplay')),
    [View.AI_QUIZ]: React.lazy(() => import('../components/AIQuiz')),
    [View.LIGHT_GUN]: React.lazy(() => import('../components/LightGunGame')),
    [View.MORSE]: React.lazy(() => import('../components/MorseMaster')),
    [View.BAND_SPEC]: React.lazy(() => import('../components/BandSpectrum')),
    [View.RADAR_VECTORS]: React.lazy(() => import('../components/Comms/RadarVectors')),
    [View.TRANSFER_DRILL]: React.lazy(() => import('../components/Comms/TransferDrill')),
    [View.METAR_BUILDER]: React.lazy(() => import('../components/Comms/MetarBuilder')),
    [View.VHF_CALC]: React.lazy(() => import('../components/VHFCalculator')),
    [View.ADV_PHRASEOLOGY]: React.lazy(() => import('../components/AdvancedPhraseology')),
    [View.RVR_SIM]: React.lazy(() => import('../components/RvrSimulator')),
    [View.RVR_CODE]: React.lazy(() => import('../components/RvrDecoder')),
    [View.CLOUD_MASTER]: React.lazy(() => import('../components/CloudMaster')),
    [View.FLIRT_TRAINER]: React.lazy(() => import('../components/FlirtTrainer')),
    [View.PAPI_VIS]: React.lazy(() => import('../components/PapiVis')),
    [View.NAV_NDB_VOR]: React.lazy(() => import('../components/Comms/MorseIdent')),
    [View.WEATHER_MINIMA]: React.lazy(() => import('../components/WeatherMinima')),
    [View.HOLDING]: React.lazy(() => import('../components/HoldEntryCalc')),
    [View.ALTIMETER]: React.lazy(() => import('../components/AltimeterLab')),
    [View.RUNWAY]: React.lazy(() => import('../components/RunwayLighting')),
    [View.SURFACE_LIGHT]: React.lazy(() => import('../components/SurfaceLighting')),
    [View.TAXIWAY_LIGHT]: React.lazy(() => import('../components/TaxiwayLighting')),
    [View.RUNWAY_MARKING]: React.lazy(() => import('../components/RunwayQuiz')),
    [View.SNOWTAM]: React.lazy(() => import('../components/SnowtamDecoder')),
    [View.SIGMET_DECODER]: React.lazy(() => import('../components/Comms/SigmetDecoder')),
    [View.WAKE_TURB]: React.lazy(() => import('../components/WakeTurbulence')),
    [View.SERVICE_CODES]: React.lazy(() => import('../components/ServiceCodes')),
    [View.NUM_TIME_TRANSMIT]: React.lazy(() => import('../components/Comms/TransmissionDrill')),
    [View.COMMS_DEFINITIONS]: React.lazy(() => import('../components/Comms/CommsDefinitions')),
    [View.INTERCEPT]: React.lazy(() => import('../components/InterceptTrainer')),

    // KSA (100)
    [View.KSA_HOME]: React.lazy(() => import('../components/GenericSubjectDashboard')),
    [View.KSA_COMPETENCIES]: React.lazy(() => import('../components/KSA/KSACoreCompetencies')),
    [View.KSA_TEM]: React.lazy(() => import('../components/KSA/TEMAdvanced')),
    [View.KSA_MENTAL_MATHS]: React.lazy(() => import('../components/KSA/MentalMathsLab')),
    [View.KSA_FORDEC]: React.lazy(() => import('../components/KSA/FORDECDecision')),
    [View.KSA_UPRT]: React.lazy(() => import('../components/KSA/UPRTConcepts')),
    [View.KSA_CRM]: React.lazy(() => import('../components/KSA/CRMScenarios')),
    [View.KSA_RESILIENCE]: React.lazy(() => import('../components/KSA/ResilienceTraining')),
    [View.KSA_PROCEDURES]: React.lazy(() => import('../components/KSA/ProcedureApplication')),

    // Ops Procedures (070)
    [View.OPS_PROC_HOME]: React.lazy(() => import('../components/GenericSubjectDashboard')),
    [View.OPS_LONG_RANGE]: React.lazy(() => import('../components/LongRangeOps')),
    [View.OPS_SPECIAL]: React.lazy(() => import('../components/SpecialOpsDashboard')),
    [View.OPS_FTL]: React.lazy(() => import('../components/FTLCalculator')),
    [View.OPS_AWO]: React.lazy(() => import('../components/AllWeatherOps')),
    [View.OPS_GENERAL]: React.lazy(() => import('../components/OpsGeneral')),

    // Simulators
    [View.MCDU_SIM]: React.lazy(() => import('../components/Simulators/MCDU/MCDU')),

    // Performance (032)
    [View.PERF_HOME]: React.lazy(() => import('../components/Performance/PerfDashboard')),
    [View.PERF_INTRO]: React.lazy(() => import('../components/Performance/PerfIntro')),
    [View.PERF_CLASS_A]: React.lazy(() => import('../components/GenericSubjectDashboard')),
    [View.PERF_CLASS_B]: React.lazy(() => import('../components/GenericSubjectDashboard')),
    [View.PERF_TAKEOFF]: React.lazy(() => import('../components/Performance/TakeoffPerf')),
    [View.PERF_CLIMB]: React.lazy(() => import('../components/Performance/ClimbPerf')),
    [View.PERF_CRUISE]: React.lazy(() => import('../components/Performance/CruisePerf')),
    [View.PERF_LANDING]: React.lazy(() => import('../components/Performance/LandingPerf')),

    // ─── PPL Track ───────────────────────────────────────────────────────────────
    [View.PPL_DASHBOARD]: React.lazy(() => import('../components/PPL/PPLDashboard')),

    // PPL specific dashboards
    [View.PPL_AIR_LAW_HOME]: React.lazy(() => import('../components/PPL/subjects/AirLaw')),
    [View.PPL_HPL_HOME]: React.lazy(() => import('../components/PPL/subjects/HumanPerformance')),
    [View.PPL_MET_HOME]: React.lazy(() => import('../components/PPL/subjects/Meteorology')),
    [View.PPL_NAV_HOME]: React.lazy(() => import('../components/PPL/subjects/Navigation')),
    [View.PPL_POF_HOME]: React.lazy(() => import('../components/PPL/subjects/PrinciplesOfFlight')),
    [View.PPL_OPS_HOME]: React.lazy(() => import('../components/PPL/subjects/OperationalProcedures')),
    [View.PPL_AGK_HOME]: React.lazy(() => import('../components/PPL/subjects/AircraftGeneralKnowledge')),
    [View.PPL_PERF_HOME]: React.lazy(() => import('../components/PPL/subjects/FlightPerformance')),

    // PPL VFR Communications → full reuse of existing Comms Dashboard (no change needed)
    [View.PPL_COMMS]: React.lazy(() => import('../components/Comms/CommsDashboard')),

    // PPL AGK Sub-modules
    [View.PPL_AGK_PISTON_ENGINE]: React.lazy(() => import('../components/AGK/PistonEnginePrinciples')), 
    [View.PPL_AGK_ELECTRICS]: React.lazy(() => import('../components/AGK/ElectricsSystem')), 
};
